--------PROC DANGKYTHITOTNGHIEP------
Alter PROC DANGKYTHITOTNGHIEP(
@NGAYLAPPHIEU DATE
)
AS
BEGIN
	DECLARE @MAPHIEU INT;
	SET @MAPHIEU= (SELECT MAX(MAPHIEU) FROM PHIEUDKTHITN);
	SET @MAPHIEU=@MAPHIEU+1;
	INSERT INTO PHIEUDKTHITN (MAPHIEU, NGAYLAPPHIEU) VALUES (@MAPHIEU, @NGAYLAPPHIEU);
END;
GO
--------------------PROC THANHTOAN-----------------
CREATE PROC THANHTOAN(
@TENHD		VARCHAR(30),
@NGAYLAP	DATE,
@TONGTIEN	FLOAT,
@MANVKT		INT,
@MAHV		INT,
@MAKH		INT,
@MAPHIEUPK	INT,
@MAPHIEUTN	INT
)
AS
BEGIN
	DECLARE @MAHD INT;
	SET @MAHD =(SELECT MAX(MAHOADON) FROM HOADON);
	IF(@MAHD IS NOT NULL)
		BEGIN
			SET	@MAHD=@MAHD+1;
		END;
	ELSE
		SET @MAHD=1;
	INSERT INTO HOADON (MAHOADON,TENHOADON,NGAYLAP,TONGTIEN,MANVKTOAN,MAHOCVIEN)
	VALUES(@MAHD, @TENHD, @NGAYLAP,@TONGTIEN, @MANVKT, @MAHV);
	IF(@MAKH IS NOT NULL)
		INSERT INTO HOADONHOCPHI (MAHOADON, MAKHOAHOC) VALUES (@MAHD, @MAKH);
	IF(@MAPHIEUPK IS NOT NULL)
		INSERT INTO HOADONPHUCKHAO (MAHOADON, MAPHIEUPHUCKHAO) VALUES (@MAHD, @MAPHIEUPK);
	IF(@MAPHIEUTN IS NOT NULL)
		INSERT INTO HOADONTHITOTNGHIEP (MAHOADON, MAPHIEUTHITN) VALUES (@MAHD, @MAPHIEUTN)
END;
-----------------DANGKYPHUCKHAO-----------------------
GO
CREATE PROC DANGKYPHUCKHAO(
@LYDO NTEXT,
@MAHV INT,
@LANTHI INT,
@MALOP INT,
@MAKH INT
)
AS
BEGIN
	DECLARE @MAPHIEUPK INT;
	SET @MAPHIEUPK =(SELECT MAX(MAPHIEUPHUCKHAO) FROM PHIEUPHUCKHAO);
	IF( @MAPHIEUPK IS NOT NULL)
		SET	@MAPHIEUPK=@MAPHIEUPK+1;
	ELSE
		SET @MAPHIEUPK=1;

	INSERT INTO PHIEUPHUCKHAO (MAPHIEUPHUCKHAO, LYDO, DIEMSAUPHUCKHAO)
	VALUES (@MAPHIEUPK, @LYDO, NULL);
	IF(@MAKH IS NOT NULL)
		INSERT INTO PHIEUPHUCKHAO_DIEMTN(MAPHIEUPHUCKHAO_DIEMTN,MAHOCVIEN, MAKHOAHOC)
		VALUES (@MAPHIEUPK, @MAHV, @MAKH);
	IF ((@MALOP IS NOT NULL) AND (@LANTHI IS NOT NULL))
		INSERT INTO PHIEUPHUCKHAO_DIEMKTHP(MAPHIEUPHUCKHAO_DIEMKTHP, MAHOCVIEN, MALOP, LANTHI)
		VALUES (@MAPHIEUPK, @MAHV, @MALOP, @LANTHI);
END;